[package]
name = "rm_grab"
version = "0.1.0"
authors = ["pegasis <admin@pegasis.site>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.10.1"
input-event-codes = "0.2.1"
